version: "3.4"

services:
  api:
    container_name: api-errors
    build:
      context: .
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3333:3333"
    depends_on:
      - mongo

  mongo:
    container_name: mongo-api
    image: mongo
    ports:
      - "27017:27017"
